# Generated by Django 5.0.6 on 2024-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('categoriaproducto', models.CharField(max_length=20)),
                ('descproducto', models.CharField(max_length=120)),
                ('stockproducto', models.CharField(max_length=3)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
