# Generated by Django 5.0.6 on 2024-07-15 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdoapp', '0002_genero_user_delete_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_genero',
            field=models.ForeignKey(db_column='id_Genero', on_delete=django.db.models.deletion.CASCADE, to='verdoapp.genero'),
        ),
    ]
