# Generated by Django 5.0.6 on 2024-07-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdoapp', '0004_remove_user_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_genero',
        ),
    ]
