# Generated by Django 5.0.6 on 2024-06-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.AutoField(db_column='idCate', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cate', models.ForeignKey(db_column='idCate', on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
