# Generated by Django 4.2.13 on 2024-06-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_initial'),
    ]

    operations = [
    ]
